# Project: Project1
# Makefile created by Dev-C++ 5.4.0

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = Food.o gameMap.o main.o Snake.o Menu.o $(RES)
LINKOBJ  = Food.o gameMap.o main.o Snake.o Menu.o $(RES)
LIBS     = -L"D:/Dev-Cpp/Dev-Cpp/MinGW32/lib" -static-libstdc++ -static-libgcc -lwinmm  -g3
INCS     = -I"D:/Dev-Cpp/Dev-Cpp/MinGW32/include"
CXXINCS  = -I"D:/Dev-Cpp/Dev-Cpp/MinGW32/include"
BIN      = Project1.exe
CXXFLAGS = $(CXXINCS)  -g3
CFLAGS   = $(INCS)  -g3
RM       = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Food.o: Food.cpp
	$(CPP) -c Food.cpp -o Food.o $(CXXFLAGS)

gameMap.o: gameMap.cpp
	$(CPP) -c gameMap.cpp -o gameMap.o $(CXXFLAGS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Snake.o: Snake.cpp
	$(CPP) -c Snake.cpp -o Snake.o $(CXXFLAGS)

Menu.o: Menu.cpp
	$(CPP) -c Menu.cpp -o Menu.o $(CXXFLAGS)
